<a href="https://colab.research.google.com/github/SankalpMehani/ml-review/blob/main/Task_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### `Task` How dimensionality reduction using Principal Component Analysis (PCA) on the Wine Quality dataset contributes to improving the classification accuracy and efficiency of wine type.

Note : Use KNN for Classification.

Data Link :  [Wine Data](https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv)

In [1]:
# Data Loading
import pandas as pd
wine_data_path = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQDVwxneOKOaJL13QMhkAhYrgWlH1tICY7RacUnj_lL8m9uUWaaUf3p7bScNyh_D2Rvt7nc1q11adSy/pub?gid=647503637&single=true&output=csv"
wine = pd.read_csv(wine_data_path)
wine.head(1)

type  fixed acidity  volatile acidity  citric acid  ...   pH  sulphates  alcohol  quality
0  white            7.0              0.27         0.36  ...  3.0       0.45      8.8        6

[1 rows x 13 columns]

In [2]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [3]:
wine.isna().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [4]:
wine.duplicated().sum()

1168

In [5]:
wine.drop_duplicates(inplace=True)
wine.shape

(5329, 13)

In [6]:
wine.dropna(inplace=True)
wine.shape

(5295, 13)

In [7]:
# Your Code goes Here
X = wine.iloc[:,1:]
y = wine['type']
X

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.0             0.270         0.36  ...       0.45      8.8        6
1               6.3             0.300         0.34  ...       0.49      9.5        6
2               8.1             0.280         0.40  ...       0.44     10.1        6
3               7.2             0.230         0.32  ...       0.40      9.9        6
6               6.2             0.320         0.16  ...       0.47      9.6        6
...             ...               ...          ...  ...        ...      ...      ...
6490            6.3             0.510         0.13  ...       0.75     11.0        6
6491            6.8             0.620         0.08  ...       0.82      9.5        6
6492            6.2             0.600         0.08  ...       0.58     10.5        5
6495            5.9             0.645         0.12  ...       0.71     10.2        5
6496            6.0             0.310         0.47  ...       0.66     11.0        6

[5295 rows x 12 columns]

In [8]:
wine['citric acid'].describe()

count    5295.000000
mean        0.318782
std         0.147112
min         0.000000
25%         0.240000
50%         0.310000
75%         0.400000
max         1.660000
Name: citric acid, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
# y_pred = knn.predict(X_test)

In [ ]:
import time

start = time.time()
y_pred = knn.predict(X_test)
print(f"Time taken: {time.time() - start} seconds")

In [ ]:

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_test, y_pred))

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
wine.iloc[:, 1:13] = scaler.fit_transform(wine.iloc[:, 1:13])
wine.head(5)

<ipython-input-11-11160e23e04c>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.23180022  0.23180022  0.23180022 ... -0.90466476 -0.90466476
  0.23180022]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  wine.iloc[:, 1:13] = scaler.fit_transform(wine.iloc[:, 1:13])


type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white      -0.165087         -0.440021     0.280208        3.477382   
1  white      -0.695163         -0.261684     0.144245       -0.766859   
2  white       0.667890         -0.380575     0.552136        0.410863   
3  white      -0.013636         -0.677803     0.008281        0.766401   
6  white      -0.770888         -0.142793    -1.079428        0.433084   

   chlorides  free sulfur dioxide  total sulfur dioxide   density        pH  \
0  -0.316815             0.838865              0.984149  2.177419 -1.401186   
1  -0.208407            -0.900220              0.314921 -0.180598  0.472180   
2  -0.181305            -0.002628             -0.301474  0.189947  0.222398   
3   0.035512             0.951064              1.265929  0.358377 -0.214721   
6  -0.316815            -0.002628              0.385366  0.122576 -0.277166   

   sulphates   alcohol  quality  
0  -0.555267 -1.475154   0.2318  
1  -0.288309 -0.885144   0.2318  
2  -0.622007 -0.379421   0.2318  
3  -0.888964 -0.547996   0.2318  
6  -0.421788 -0.800857   0.2318

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [75]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(classification_report(y_test, y_pred))



Accuracy: 0.9291784702549575
              precision    recall  f1-score   support

         red       0.88      0.85      0.86       275
       white       0.95      0.96      0.95       784

    accuracy                           0.93      1059
   macro avg       0.91      0.90      0.91      1059
weighted avg       0.93      0.93      0.93      1059



array(['white', 'white', 'white', ..., 'white', 'white', 'white'],
      dtype=object)

In [15]:
covariance_matrix = X_train.cov()
covariance_matrix

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.699974          0.048369     0.059949   
volatile acidity           0.048369          0.028367    -0.009560   
citric acid                0.059949         -0.009560     0.021666   
residual sugar            -0.620372         -0.124740     0.100208   
chlorides                  0.014293          0.002371     0.000293   
free sulfur dioxide       -6.591860         -1.076039     0.358360   
total sulfur dioxide     -24.223390         -3.925969     1.719757   
density                    0.001857          0.000158     0.000039   
pH                        -0.055568          0.006766    -0.008175   
sulphates                  0.058741          0.005678     0.001306   
alcohol                   -0.185441         -0.014546    -0.002451   
quality                   -0.104853         -0.039414     0.011015   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity              -0.620372   0.014293            -6.591860   
volatile acidity           -0.124740   0.002371            -1.076039   
citric acid                 0.100208   0.000293             0.358360   
residual sugar             20.473802  -0.020518            31.661106   
chlorides                  -0.020518   0.001384            -0.129285   
free sulfur dioxide        31.661106  -0.129285           321.859959   
total sulfur dioxide      124.894930  -0.589184           730.876589   
density                     0.007160   0.000042             0.000015   
pH                         -0.165750   0.000154            -0.409167   
sulphates                  -0.121013   0.002300            -0.522013   
alcohol                    -1.666148  -0.011936            -3.487509   
quality                    -0.245503  -0.006671             0.832851   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                   -24.223390  0.001857 -0.055568   0.058741   
volatile acidity                 -3.925969  0.000158  0.006766   0.005678   
citric acid                       1.719757  0.000039 -0.008175   0.001306   
residual sugar                  124.894930  0.007160 -0.165750  -0.121013   
chlorides                        -0.589184  0.000042  0.000154   0.002300   
free sulfur dioxide             730.876589  0.000015 -0.409167  -0.522013   
total sulfur dioxide           3182.679638  0.001279 -1.998488  -2.362907   
density                           0.001279  0.000009  0.000020   0.000124   
pH                               -1.998488  0.000020  0.025961   0.004145   
sulphates                        -2.362907  0.000124  0.004145   0.022528   
alcohol                         -16.344999 -0.002367  0.020013  -0.003843   
quality                          -2.243985 -0.000866  0.005182   0.005408   

                        alcohol   quality  
fixed acidity         -0.185441 -0.104853  
volatile acidity      -0.014546 -0.039414  
citric acid           -0.002451  0.011015  
residual sugar        -1.666148 -0.245503  
chlorides             -0.011936 -0.006671  
free sulfur dioxide   -3.487509  0.832851  
total sulfur dioxide -16.344999 -2.243985  
density               -0.002367 -0.000866  
pH                     0.020013  0.005182  
sulphates             -0.003843  0.005408  
alcohol                1.386111  0.486865  
quality                0.486865  0.748704

In [30]:
eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)
print(f'''eigenvalues: \n {eigenvalues} \n shape: {eigenvalues.shape}
\n\n eigenvectors: \n {eigenvectors} \n shape: {eigenvectors.shape}''')

eigenvalues: 
 [3.36383248e+03 1.45989226e+02 1.55781515e+01 1.80240817e+00
 1.21029107e+00 4.56842498e-01 3.16071406e-02 2.04423664e-02
 1.52160646e-02 1.05885268e-02 8.52881184e-04 5.95929956e-07] 
 shape: (12,) 


 eigenvectors: 
 [[-7.46450447e-03 -5.10830608e-03 -2.69209580e-02  7.08527703e-01
   6.98869606e-01 -5.49379690e-02  3.65673421e-02 -2.76130552e-02
   5.12624171e-02 -3.18511152e-02 -1.42090874e-03  1.01838733e-03]
 [-1.21013583e-03 -8.74153667e-04 -2.37754210e-03  2.50574865e-02
  -2.02562864e-02 -4.16611436e-02  6.33902932e-01 -3.38093947e-01
  -3.98853929e-01  5.63140183e-01  6.97245352e-02  2.23493786e-03]
 [ 5.22598779e-04 -3.69175234e-04 -2.20924416e-03  2.31070167e-02
   5.14479439e-02  6.31690189e-03 -4.17207393e-01  4.80862001e-01
   1.95621961e-02  7.67122825e-01  5.12209194e-02  1.36333716e-04]
 [ 3.85087823e-02  1.18631773e-02 -9.96039684e-01 -6.90310215e-02
   2.98310235e-02 -2.41479357e-02  4.20036366e-03  3.46414555e-03
   2.53493289e-03 -2.51979947e-03 -6.

In [39]:
pc = eigenvectors[0:3]
pc

array([[-7.46450447e-03, -5.10830608e-03, -2.69209580e-02,
         7.08527703e-01,  6.98869606e-01, -5.49379690e-02,
         3.65673421e-02, -2.76130552e-02,  5.12624171e-02,
        -3.18511152e-02, -1.42090874e-03,  1.01838733e-03],
       [-1.21013583e-03, -8.74153667e-04, -2.37754210e-03,
         2.50574865e-02, -2.02562864e-02, -4.16611436e-02,
         6.33902932e-01, -3.38093947e-01, -3.98853929e-01,
         5.63140183e-01,  6.97245352e-02,  2.23493786e-03],
       [ 5.22598779e-04, -3.69175234e-04, -2.20924416e-03,
         2.31070167e-02,  5.14479439e-02,  6.31690189e-03,
        -4.17207393e-01,  4.80862001e-01,  1.95621961e-02,
         7.67122825e-01,  5.12209194e-02,  1.36333716e-04]])

In [49]:
transformed_df = np.dot(X_train, pc.T)
transformed_df.shape

(4236, 3)

In [50]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
pca.fit_transform(X_train)

array([[ 31.99822237, -20.32905818,  -4.93848435],
       [ -8.88365874,   1.91397846,  -3.17085376],
       [ 65.47627443, -22.23809225,  -5.97979325],
       ...,
       [-27.68842938,  -7.93280597,  -2.02363747],
       [-56.15308878,   6.10902977,  -0.71670087],
       [ -9.01313157,   5.08933857,   0.56097324]])

In [52]:
pca.transform(X_test)

array([[ 4.20289759e+01,  8.24458039e+00, -5.07563702e+00],
       [-5.95527304e+00, -2.29113651e+01, -2.22617549e+00],
       [-3.86476568e+01, -2.74120910e-02,  6.04662075e-01],
       ...,
       [-8.80616084e+00,  1.45840548e+01, -3.62526468e+00],
       [-1.62188202e+01, -9.35184394e+00, -2.24549942e+00],
       [ 6.75234328e+01, -3.33624845e+01, -4.93081935e+00]])